branches: [ main, test ]

pipelines:
  download_dependencies:
    image: python:latest
    commands:
      - pip install --upgrade pip
      - pip install poetry
      - poetry install

  lint:
    image: python:latest
    commands:
      - poetry run autopep8 -i *.py -r -a

  test:
    image: python:latest
    commands:
      - poetry run pytest


  deploy:
    image: node:latest
    when:
      branches: main
    commands:
      - npm i -g @railway/cli
      - TOKEN=$${RAILWAY_TOKEN} railway link
      - TOKEN=$${RAILWAY_TOKEN} railway up
    secrets: [ railway_token ]

