image: python:alpine

pipelines:
  branches:
    main:
      - step:
          name: Download dependencies
          script:
            - pip install poetry -U
            - poetry install --no-root

      - step:
          name: Deploy
          image: node:latest
          script:
            - npm i -g @railway/cli
            - TOKEN=$RAILWAY_TOKEN railway link 20db06f1-b811-475e-a7f9-6efcef7029a7
            - TOKEN=$RAILWAY_TOKEN railway up

    test:
      - step:
          name: Download dependencies and Test
          script:
            - poetry install
            - pytest
          caches:
            - poetry

      - step:
          name: Lint code
          script:
            - pip install autopep8
            - autopep8 -i *.py -r -a

