image: python:3.8

pipelines:
  test:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - pytest
      - step:
          name: Lint code
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
