name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        script: pip install --upgrade pip

      - name: Install formatter
        script: pip install autopep8

      - name: Formatting
        script: autopep8 -i *.py -r -a

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Testing app
        run: poetry run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'main'
    steps:
      - name: Nodejs setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install railway-cli
        script: npm i -g @railway/cli

      - name: Set environment
        script: TOKEN=token railway link 20db06f1-b811-475e-a7f9-6efcef7029a7
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to railway
        script: TOKEN=token railway up
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}

