name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Poetry setup
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.2

      - name: Install dependencies
        run: poetry install

      - name: Testing
        run: poetry run pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t ghcr.io/ftcserhiy/naurok-backend .

      - name: Push docker image
        run: docker push ghcr.io/ftcserhiy/naurok-backend:latest
        
