name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install linter
        run: pip3 install autopep8

      - name: Lint
        run: autopep8 -i *.py -r -a

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry install

      - name: Testing
        run: poetry run pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Nodejs setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install railway cli
        run: npm i -g @railway/cli

      - name: Set project link
        run: TOKEN=token railway link 20db06f1-b811-475e-a7f9-6efcef7029a7
        env:
          token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy
        run: TOKEN=token railway up
        env:
          token: ${{ secrets.RAILWAY_TOKEN }}
        
